[workspace]
resolver = "2"
members = ["crates/petra-core", "crates/petra-deck", "crates/petra-io", "crates/petra-wasm", "crates/petra-cli", "crates/petra-observables"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
rand = "0.8"
rand_pcg = "0.3"
thiserror = "1"
